spring:
  datasource:
    url: jdbc:mysql://localhost:6969/budget_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
app:
  host: 127.0.0.1
  port: 1234

